2018-06-12 11:57:25,658 ERROR: Exception on /index [GET] [in /home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/palpatine222/Documents/2018/microblog/app/routes.py", line 66, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/palpatine222/Documents/2018/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/palpatine222/Documents/2018/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/palpatine222/Documents/2018/microblog/app/templates/index.html", line 6, in block "content"
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2018-06-12 11:57:44,816 ERROR: Exception on /index [GET] [in /home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/palpatine222/Documents/2018/microblog/app/routes.py", line 66, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/palpatine222/Documents/2018/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/palpatine222/Documents/2018/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/palpatine222/Documents/2018/microblog/app/templates/index.html", line 6, in block "content"
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2018-06-12 11:57:48,968 INFO: Microblog startup [in /home/palpatine222/Documents/2018/microblog/app/__init__.py:45]
2018-06-12 11:57:51,163 ERROR: Exception on /index [GET] [in /home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/palpatine222/Documents/2018/microblog/app/routes.py", line 66, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/palpatine222/Documents/2018/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/palpatine222/Documents/2018/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/palpatine222/Documents/2018/microblog/app/templates/index.html", line 6, in block "content"
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/home/palpatine222/Documents/2018/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
